# Generated by Django 3.1.5 on 2021-01-17 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_auto_20210117_2000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='experince',
            new_name='experience',
        ),
    ]
