# Generated by Django 3.1.5 on 2021-01-18 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_remove_job_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('raised', 'raised'), ('disable', 'disable')], default='active', max_length=20),
        ),
    ]
